# Generated by Django 5.2.2 on 2025-06-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0002_default_site")]

    operations = [
        migrations.AlterField(
            model_name="user", name="birth_date", field=models.DateField(blank=True)
        )
    ]
