# Generated by Django 5.2.2 on 2025-06-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0003_alter_user_birth_date")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        )
    ]
