# Generated by Django 5.2.8 on 2025-11-29 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0025_alter_user_user_type")]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "is_system",
                    models.BooleanField(
                        default=False, help_text="System roles cannot be deleted"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sphere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="db_main.sphere",
                    ),
                ),
            ],
            options={
                "db_table": "role",
                "ordering": ["name"],
                "unique_together": {("sphere", "name")},
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("read", "READ"),
                            ("create", "CREATE"),
                            ("update", "UPDATE"),
                            ("delete", "DELETE"),
                            ("approve", "APPROVE"),
                            ("reject", "REJECT"),
                            ("schedule", "SCHEDULE"),
                            ("publish", "PUBLISH"),
                            ("manage", "MANAGE"),
                            ("manage_permissions", "MANAGE_PERMISSIONS"),
                            ("*", "ALL"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("sphere", "SPHERE"),
                            ("event", "EVENT"),
                            ("proposal", "PROPOSAL"),
                            ("category", "CATEGORY"),
                            ("session", "SESSION"),
                            ("space", "SPACE"),
                            ("venue", "VENUE"),
                            ("*", "ALL"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="db_main.role",
                    ),
                ),
            ],
            options={
                "db_table": "role_permission",
                "indexes": [
                    models.Index(
                        fields=["role", "action", "resource_type"],
                        name="role_permis_role_id_d640ed_idx",
                    )
                ],
                "unique_together": {("role", "action", "resource_type")},
            },
        ),
        migrations.CreateModel(
            name="UserPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("read", "READ"),
                            ("create", "CREATE"),
                            ("update", "UPDATE"),
                            ("delete", "DELETE"),
                            ("approve", "APPROVE"),
                            ("reject", "REJECT"),
                            ("schedule", "SCHEDULE"),
                            ("publish", "PUBLISH"),
                            ("manage", "MANAGE"),
                            ("manage_permissions", "MANAGE_PERMISSIONS"),
                            ("*", "ALL"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("sphere", "SPHERE"),
                            ("event", "EVENT"),
                            ("proposal", "PROPOSAL"),
                            ("category", "CATEGORY"),
                            ("session", "SESSION"),
                            ("space", "SPACE"),
                            ("venue", "VENUE"),
                            ("*", "ALL"),
                        ],
                        max_length=50,
                    ),
                ),
                ("resource_id", models.PositiveIntegerField()),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who granted this permission",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "granted_from_role",
                    models.ForeignKey(
                        blank=True,
                        help_text="Role this permission was copied from",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="db_main.role",
                    ),
                ),
                (
                    "sphere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_permissions",
                        to="db_main.sphere",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_permission",
                "indexes": [
                    models.Index(
                        fields=["user", "sphere"], name="user_permis_user_id_6fbecf_idx"
                    ),
                    models.Index(
                        fields=["action", "resource_type", "resource_id"],
                        name="user_permis_action_54bacd_idx",
                    ),
                ],
                "unique_together": {
                    ("user", "sphere", "action", "resource_type", "resource_id")
                },
            },
        ),
    ]
