# Generated by Django 5.2.7 on 2025-11-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0025_alter_user_user_type")]

    operations = [
        migrations.AddField(
            model_name="space",
            name="location_label",
            field=models.CharField(
                blank=True,
                help_text="Optional label to display instead of name (e.g. 'Room 3 (Main Building)')",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="space",
            name="location_url",
            field=models.URLField(
                blank=True,
                help_text="Optional URL for the location (e.g. Google Maps link)",
            ),
        ),
    ]
