# Generated by Django 5.2.7 on 2025-11-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0026_event_location_label_event_location_url")]

    operations = [
        migrations.AddField(
            model_name="sphere",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Description shown on the overview page",
            ),
        )
    ]
