# Generated by Django 5.2.6 on 2025-11-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0028_sphere_visibility")]

    operations = [
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.ImageField(
                blank=True, help_text="Cover image for the event", upload_to="events"
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Cover image for the session",
                upload_to="sessions",
            ),
        ),
        migrations.AddField(
            model_name="sphere",
            name="image",
            field=models.ImageField(
                blank=True, help_text="Cover image for the sphere", upload_to="spheres"
            ),
        ),
    ]
