# Generated by Django 5.2.7 on 2025-11-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0029_event_image_session_image_sphere_image")]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="location_url",
            field=models.URLField(
                blank=True,
                help_text="Optional URL for the location (e.g. Google Maps link)",
                max_length=500,
            ),
        )
    ]
