# Generated by Django 6.0.1 on 2026-01-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0032_add_allow_custom_to_fields")]

    operations = [
        migrations.AddField(
            model_name="proposalcategory",
            name="time_slots",
            field=models.ManyToManyField(blank=True, to="db_main.timeslot"),
        )
    ]
