# Generated by Django 6.0.1 on 2026-02-01 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0032_add_allow_custom_to_fields")]

    operations = [
        migrations.CreateModel(
            name="TicketAPIIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        help_text="Registered provider, e.g. 'kapitularz'",
                        max_length=50,
                    ),
                ),
                ("base_url", models.URLField(max_length=500)),
                ("encrypted_secret", models.TextField()),
                ("timeout", models.PositiveIntegerField(default=30)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sphere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_api_integrations",
                        to="db_main.sphere",
                    ),
                ),
            ],
            options={"db_table": "ticket_api_integration"},
        )
    ]
