# Generated by Django 6.0.2 on 2026-02-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0037_remove_space_event_fk")]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="rejected",
            field=models.BooleanField(default=False),
        )
    ]
