# Generated by Django 6.0.2 on 2026-02-14 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0037_remove_space_event_fk")]

    operations = [
        migrations.CreateModel(
            name="DiscountTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("percentage", models.PositiveIntegerField()),
                ("threshold", models.PositiveIntegerField()),
                (
                    "threshold_type",
                    models.CharField(
                        choices=[("hours", "Hours"), ("agenda_items", "Agenda Items")],
                        max_length=20,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discount_tiers",
                        to="db_main.event",
                    ),
                ),
            ],
            options={
                "db_table": "discount_tier",
                "ordering": ["-percentage"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("percentage__gte", 1), ("percentage__lte", 100)
                        ),
                        name="discount_tier_percentage_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("threshold__gte", 1)),
                        name="discount_tier_threshold_positive",
                    ),
                ],
            },
        )
    ]
