# Generated by Django 6.0.4 on 2026-05-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_main", "0074_alter_hostpersonaldata_value_and_more")]

    operations = [
        migrations.AddField(
            model_name="connection",
            name="last_tested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="connection",
            name="last_tested_detail",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="connection",
            name="last_tested_status",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
